version: "3"
services:
  postgres15:
    image: postgres:15-alpine
    container_name: postgres15
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=jpasampledb
